# --- PostgreSQL ---
postgresql-hostname: guacdb
postgresql-port: 5432
postgresql-database: guacamole_db
postgresql-username: guacamole
postgresql-password: guacamole
postgresql-default-schema: public

# --- OpenID ---
openid-issuer: http://localhost:8080/auth/realms/platform
openid-client-id: guacamole
openid-redirect-uri: http://localhost:8081/guacamole
openid-username-claim-type: preferred_username

# --- Extensions ---
extension-priority: openid,postgresql
openid-logout-uri: http://172.26.197.98:8090/realms/platform/protocol/openid-connect/logout?redirect_uri=http://172.26.197.98:8081/guacamole
